### PR TITLE
Fix ja translations

### LINKED ISSUE #268: Update Japanese translation
Hi,
we use this plugin in Japanese, but I want to fix Japanese transation for "n month(s) ago".

e.g. ) `Japanese translation for "1 month ago" (n = 1)`
now translation) "1 月前"
correct transation) "1 ヶ月前"

So now translations miss "ヶ", so I want to add it to some translation in `locales/jquery.timeago.ja.js`. (c.f. [google translation](https://translate.google.co.jp/?ie=UTF-8&hl=ja&client=tw-ob#en/ja/1%20month%20ago ))

If you would like to do, I prepare to make pull request. Could you tell me what you think about it, please?

### PR DESCRIPTION
**Pull request by yoshihara**
closes #268

### CODE REVIEW

**Comment by rmm5t** [comment]
Thank you!

**Comment by yoshihara** [comment]
Thank you for merge! I wait for release of new version!

**Comment by rmm5t** [comment]
I don't normally release new versions for locale updates. Are you using a package manager that would benefit by a version bump?

**Comment by yoshihara** [comment]
Oh, sorry i misunderstood about release. Hmm, we use `npm` for package maneger, so i think that release is needed to use this plugin with updated Japanese locale normally.

**Comment by rmm5t** [comment]
No, it's a fair expectation to expect a new versioned release, especially with the abundance of javascript package managers nowadays. I just published `v1.5.1`. Enjoy.

**Comment by yoshihara** [comment]
I'm glad you release `v1.5.1` soon :joy: Thank you!

**Pull request merged**
