### PR TITLE
update locale fr to match template locale en

### PR DESCRIPTION
**Pull request by althio**
update locale-fr to better match template locale-en
both standard and short version

If possible @dgageot @Krule previous contributors please review.

### CODE REVIEW

**Comment by rmm5t** [comment]
Closing for same reason as #211.

**Comment by althio** [comment]
Do you derive also the locales from http://apidock.com/rails/v4.1.8/ActionView/Helpers/DateHelper/distance_of_time_in_words and could you point me where I can find them?

**Comment by rmm5t** [comment]
Not specifically. All locale translations were done by volunteers and not necessarily vetted in any other way. Consider them `contrib`.

However, you bring up a very interesting point, and Rails has come a long way with regards to i18n since this js library was written.

This should help:
https://github.com/svenfuchs/rails-i18n/tree/master/rails/locale

Search for the `distance_in_words` key.

**Comment by althio** [comment]
There are 'environ' in almost every line in French, much more than 'about'
occurrences in English.
This is not very satisfying IMO as a default but I understand this is not
exactly the upstream source and the place to discuss.

**Comment by rmm5t** [comment]
I understand your frustration. I've long had plans to consider a major refactor to timeago.js, where I would try to solve a lot of previous requests and these kinds of inconsistencies. I just never find the time to dig in for the "big rewrite."

**Comment by althio** [comment]
I don't think I will have the courage to track down every upstream version and discuss there.
I also didn't understand what is the ultimate source for jquery.timeago.fr-short.js
In any case jquery.timeago.fr-short.js looks very different from jquery.timeago.en-short.js as shortened.

Please compare shortened version for different languages.
https://github.com/rmm5t/jquery-timeago/blob/master/locales/jquery.timeago.en-short.js
https://github.com/rmm5t/jquery-timeago/blob/master/locales/jquery.timeago.es-short.js
https://github.com/rmm5t/jquery-timeago/blob/master/locales/jquery.timeago.pt-br-short.js
https://github.com/rmm5t/jquery-timeago/blob/master/locales/jquery.timeago.fr-short.js
The french one stands out.

**Comment by rmm5t** [comment]
Again, every translation in the `locales` directory should be considered "contrib." In fact, it might have been better if I had named it `contrib/locales` to convey that better. 

They are effectively contributions by volunteers that I don't fully support simply because I don't speak any of the languages to be able to adequately judge the quality of any of them.

**Comment by rmm5t** [comment]
The "short" versions are even more unique. They have no root in anything. Just something that others thought might be useful to share.

**Pull request closed without merging**
