### PR TITLE
consistant use of 'about' for singular and plural

### PR DESCRIPTION
**Pull request by althio**
use 'about' for all singular strings
do not use 'about' for all plural strings

### CODE REVIEW

**Comment by rmm5t** [comment]
What? Why? The goal of this gem was to mimic Rails's `distance_of_time_in_words` helper, and with that in mind, I can't accept this.  You're welcome to override the settings, of course.

* "Something happened about a day ago" is much more accurate than "...happened a day ago" because both would display up until 42 hours have passed.

**Comment by rmm5t** [comment]
Oh, I'm sorry. I might have misunderstood.  Were you trying to make those templates match the underlying defaults?

**Comment by rmm5t** [comment]
I doubled check the Rails `time_ago_in_words` helper and since we're trying to stay consistent with that, I'm going to keep this closed. Sorry for the mix-up above.

**Comment by althio** [comment]
> "Something happened about a day ago" is much more accurate than "...happened a day ago" because both would display up until 42 hours have passed.

My point exactly.
"about a day ago" seems more desirable but that is not what is offered right now if I am not mistaken. Override settings, why not.

Thanks for the reference and the 'historical' explanation anyway.

**Pull request closed without merging**
