### PR TITLE
handle slovenian translation correctly

### PR DESCRIPTION
**Pull request by iElectric**
We have a bit more cases to handle than we currently do.

cc @mclion

### CODE REVIEW

**Comment by rmm5t** [comment]
This is awesome. Thank you. Considering I don't know any Slovenian, and there are a lot of requested changes here, could you please get at least one other person to +1 this and verify it helps move things in the correct direction?

**Comment by iElectric** [comment]
Maybe someone will. Meanwhile you can see the plural formula for Slovenian here: https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html

**Comment by offlinehacker** [comment]
+1 looks correct to me

**Comment by brodul** [comment]
Seems legit.

Fiddle with the new translations. (may not work months from now)
http://jsfiddle.net/gm75oaz8/1/


Pitch for testing (in slovene):

"Pikci, dajte stestirat."

**Comment by mclion** [comment]
Yeah, this code is better. It's by the book. It's the formula you get in poedit, when you switch to slovenan dictionary, if you want to check.

**Comment by rmm5t** [comment]
Rock on. Thanks everyone! :beers:

**Pull request merged**
