### PR TITLE
Change suffix/prefix Ago to FromNow for locale 'pt'

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by rmm5t** [comment]
Thanks for looking to help improve the locale here, but I’m going to need an explanation why thw new version is better than the old. 

Also, why is the new capitalized?

**Comment by pedro-mendonca** [comment]
Hi @rmm5t,

Sorry for the lack of contextualization :)

As for Greek, in Portuguese it's correct to say:
"Há 2 minutos" (concatenation of Prefix + time)
Rather than the current solution:
"2 minutos atrás" (concatenation of time + sufix)

The captizalization is because it's the beginning of the sentence.

**Comment by rmm5t** [comment]
> As for Greek, in Portuguese it's correct to say:
> "Há 2 minutos" (concatenation of Prefix + time)

Okay, I'll have to take your word on this. Can you please explain why you think the original transaction is incorrect? Also, could you explain the difference between the `pt` transaction and the Brazilian transaction equivalent?
https://github.com/rmm5t/jquery-timeago/blob/master/locales/jquery.timeago.pt-br.js

> The captizalization is because it's the beginning of the sentence.

Okay, but timeago isn't designed to be used as a full sentence. It's designed to be used as a sentence fragment. If you're using it in a sentence and need the capitalization, you'll need to override the settings for your specific use-case.

Please remove the capitalization in this PR, and I'll merge it in.

**Comment by pedro-mendonca** [comment]
I'll put a link here from a very well known portuguese site to explain linguistic issues, with the info for future reference, but I'll try to translate it :)
https://ciberduvidas.iscte-iul.pt/artigos/rubricas/idioma/ha-anos-atras/2346
The original Portuguese text:

> Nestas frases, o verbo haver significa «existir» e usa-se para indicar a existência de um período que decorreu desde o momento em que se passou a acção referida até ao momento em que a frase é proferida. O verbo haver no presente do indicativo («há») indica o tempo presente, indica o que acontece no presente (e não atrás), o que acontece ou o que existe no momento em que se está a falar: no caso da expressão «há dez anos», tal significa que no momento em que a frase está a ser proferida (hoje) existem dez anos, completaram-se dez anos desde que algo aconteceu.

I hope this is a fair translation :)
_In these sentences, the verb "haver (há)" means "to exist" and is used to say that there exist a period of time since the moment the action ocurred to current moment of the sentence is said. The verb (in the present) "há" means what happens now as we speak in the present, and not in the past: in the case of the expression «há 10 anos», it means that from now (today), exists a period of 10 years since something happen._

About the **pt-br**, I don't know if the use case is similiar or not, I'm not a brazilian portuguese speaker, so I'll probably leave that out of the changes until you have some native brazilian user that suggest you any change.

If it helps, since I found your plugin as a submodule of a WordPress plugin and that's how I found the _error_, I can show you what are the options that both WordPress Translation Teams have chosen to translate strings like this `"%s ago"`:
PT: [`"Há %s"`](https://translate.wordpress.org/consistency?search=%25s+ago&set=pt%2Fdefault&project=1)
PT-BR: [`"%s atrás"`](https://translate.wordpress.org/consistency?search=%25s+ago&set=pt-br%2Fdefault&project=1)

About the Capitalization, I think it's fine, I'll remove it, as this is a library, the parent software can and should take care of that with CSS depending of the use case, if it's a standalone sentence or if it's concatenated with a another sentence.

I'll push a commit to remove the capitalization in a minute.

Thanks :)

**Comment by rmm5t** [comment]
Thank you!

🍻

**Comment by pedro-mendonca** [comment]
Thank You!

**Pull request merged**
